Deeper refactoring
fgm/rabbitmq pull request #13
Opened 2017-08-21 16:27 UTC by phcorp

2017-08-21 19:03 UTC, FGM commented on rabbitmq.drush.inc
> +  $queueFactory = \Drupal::service('queue');
drupalcs throws warnings on static method calls, hence the silly looking code creating a Drupal instance.

2017-08-21 19:04 UTC, FGM commented on rabbitmq.drush.inc
> +  $consumer = \Drupal::service('rabbitmq.consumer');
idem

2017-08-21 19:04 UTC, FGM commented on rabbitmq.drush.inc
> +    return (int) drush_get_option($name, Consumer::OPTIONS[$name]);
Any advantage in using the cast over the function call ?

2017-08-21 19:05 UTC, FGM commented on rabbitmq.drush.inc
> +      'Worker for queue @name does not implement the worker interface.',
Good idea to replace the double quotes by single quotes, but the line length is not limited outside arrays and comments, so no line wrapping is expected after the "dt("

2017-08-21 19:05 UTC, FGM commented on rabbitmq.drush.inc
> +      'Could not obtain channel for queue.',
idem

2017-08-21 19:06 UTC, FGM commented on src/ConnectionWrapper.php
> +class ConnectionWrapper {
Any reason to rename that class ? There is no collision in the namespace, so what is the point ?

2017-08-21 19:07 UTC, FGM commented on src/Consumer.php
> +        $channel->basic_consume(
same as dt() calls above

2017-08-21 19:08 UTC, FGM commented on src/Consumer.php
> +   * @param \Drupal\rabbitmq\Queue\queue $queue
Uppercase needed for PSR4 compliance.

2017-08-21 19:08 UTC, FGM commented on src/Consumer.php
> +  protected function getChannel(queue $queue): AMQPChannel {
idem

2017-08-21 19:09 UTC, FGM commented on src/Consumer.php
> +  protected function hitIterationsLimit(int $maxIterations, int $iteration): bool {
Much as I regret it, result type hints have been voted against in D8 coding standards, although static type parameter hints have been allowed. So...

2017-08-21 19:09 UTC, FGM commented on src/Consumer.php
> +        'RabbitMQ worker has reached max number of iterations: @count. Exiting.',
same at "dt("

2017-08-21 19:12 UTC, fgm requested changes
Lots of interesting things, but some coding standards breaks. Could you split it in two, putting the simple reformatting things in one PR, then the main one refactoring the consume() method in another one to make it easier to reason about ?

2017-08-22 11:22 UTC, phcorp commented on rabbitmq.drush.inc
> +    return (int) drush_get_option($name, Consumer::OPTIONS[$name]);
According to PHP Inspections (EA Extended), type casting [can be up to 6 times faster](https://github.com/kalessil/phpinspectionsea/blob/master/src/test/resources/fixtures/api/type-casting-php4-functions.php).
https://3v4l.org/E7soS

2017-08-22 11:26 UTC, phcorp commented on src/ConnectionWrapper.php
> +class ConnectionWrapper {
The actual connection is stored inside the object instanciating this class, so the class was renamed for clarity. Elsewhere in the module, an instance of this class is stored in a `$connection_factory` variable whose name does not seem to suit with its actual purpose.

2017-08-22 12:29 UTC, FGM commented on rabbitmq.drush.inc
> +    return (int) drush_get_option($name, Consumer::OPTIONS[$name]);
Sold!

2017-08-22 14:29 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/c89e2512-6e69-42ea-a415-bacc0db37ff2) was created.

2017-08-22 14:31 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/c89e2512-6e69-42ea-a415-bacc0db37ff2) completed: **115 Issues, 5 Patches**

2017-08-22 14:31 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/a2857b29-cb94-4077-a965-f042897f6d6c) was created.

2017-08-22 14:33 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/a2857b29-cb94-4077-a965-f042897f6d6c) completed: **2 new issues**

2017-08-22 14:44 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/1c22d4d9-016f-4b20-8e00-cd3603d25098) was created.

2017-08-22 14:45 UTC, phcorp commented
I removed reformatting things outside the PR.

2017-08-22 14:48 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/1c22d4d9-016f-4b20-8e00-cd3603d25098) completed: **11 new issues, 1 updated code elements**

2017-08-22 14:51 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/9b7f4926-68c6-4e5c-894e-d334d4ee931b) was created.

2017-08-22 14:53 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/7694ff8d-23f6-4509-b247-6daeb01cec27) was created.

2017-08-22 14:54 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/9b7f4926-68c6-4e5c-894e-d334d4ee931b) completed: **118 Issues, 5 Patches**

2017-08-22 14:56 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/7694ff8d-23f6-4509-b247-6daeb01cec27) completed: **118 Issues, 5 Patches**

2017-08-22 17:03 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/d5831a37-180e-48c5-97ac-5ad6e4b43f1c) was created.

2017-08-22 17:05 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/d5831a37-180e-48c5-97ac-5ad6e4b43f1c) completed: **No new issues**

2017-08-22 17:13 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/c6961527-f387-4051-a3a9-f04b29918efb) was created.

2017-08-22 17:15 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/c6961527-f387-4051-a3a9-f04b29918efb) completed: **No new issues**

2017-08-22 17:15 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/56027f76-6c33-463b-b042-f8cf8a9d3483) was created.

2017-08-22 17:17 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/56027f76-6c33-463b-b042-f8cf8a9d3483) completed: **No new issues**

2017-08-22 17:22 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/fe40c322-d35e-4bff-b474-e1bb51f0439a) was created.

2017-08-22 17:24 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/fe40c322-d35e-4bff-b474-e1bb51f0439a) completed: **115 Issues, 2 Patches**

2017-08-29 14:25 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/3bf862b9-cb89-495a-b034-fc0364dbd116) was created.

2017-08-29 14:29 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/3bf862b9-cb89-495a-b034-fc0364dbd116) completed: **1 updated code elements**

2017-08-29 15:02 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/90bc0c09-7403-4455-8e0b-325c565c9e9b) was created.

2017-08-29 15:05 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/90bc0c09-7403-4455-8e0b-325c565c9e9b) completed: **1 new issues, 1 updated code elements**

2017-08-29 15:06 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/8ea6ed32-bf16-4d17-b45a-f8fe522f17ec) was created.

2017-08-29 15:10 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/8ea6ed32-bf16-4d17-b45a-f8fe522f17ec) completed: **1 updated code elements**

2017-08-30 12:08 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FGM/rabbitmq/inspections/bb6585d9-e96e-46b7-8eeb-02ae5b2b9688) was created.

2017-08-30 14:08 UTC, FGM commented
Rebased and merged manually into #14

2017-08-30 14:08 UTC, closed without merging